# This is a basic workflow to help you deploy an ADF ARM template to a higher environment

# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches:
      - adf_publish
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    name: 'This deploys to Production'
    steps:
    - uses: actions/checkout@v3
      with:
          ref: adf_publish

    - name: Az Powershell Installation
      run: Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
      shell: pwsh
      
    - name: Azure Login
      uses: Azure/login@v1.4.3
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{secrets.AZURE_CREDENTIALS}}


    - name: Pre-deployment
      shell: pwsh
      run: pwsh -File ./dev-adf-vinayak/PrePostDeploymentScript.ps1 -armTemplate "./dev-adf-vinayak/ARMTemplateForFactory.json" -ResourceGroupName vinayak-RG -DataFactoryName prod-adf-vinayak -predeployment $true -deleteDeployment $false

    
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1.0.6
      with:
        # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
        scope: 'resourcegroup'
        # Target resource group of the deployment.
        resourceGroupName: 'vinayak-RG'
        # Specify the path to the ADF ARM template. In this scenario, the workflow is in the same branch, 
        # hence we only add the folder and arm template name to the path
        template: ./dev-adf-vinayak/ARMTemplateForFactory.json
        # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
        deploymentMode: Incremental
        # Supply deployment parameter values. In this simple scenario, 
        # I am only passing the name of the target ADF to which this is being deployed
        parameters: factoryName=prod-adf-vinayak


    - name: Post-deployment
      shell: pwsh
      run: pwsh -File ./dev-adf-vinayak/PrePostDeploymentScript.ps1 -armTemplate "./dev-adf-vinayak/ARMTemplateForFactory.json" -ResourceGroupName vinayak-RG -DataFactoryName prod-adf-vinayak predeployment $false -deleteDeployment $true
    
